# Generated by Django 4.0.5 on 2022-06-19 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
