# Generated by Django 4.0.5 on 2022-06-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Note',
        ),
    ]
