# Generated by Django 4.0.5 on 2022-06-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_name_post_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.TextField(max_length=50),
        ),
    ]
