# Generated by Django 4.0.5 on 2022-06-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_post_complete_post_incomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Incomplete',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Complete',
        ),
    ]
