# Generated by Django 4.0.5 on 2022-06-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_incomplete_post_status_remove_post_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.TextField(max_length=18),
        ),
    ]
