# Generated by Django 4.0.5 on 2022-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_post_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.CharField(max_length=18),
        ),
    ]
