# Generated by Django 4.0.5 on 2022-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
